"""Report generation services for PDF, Excel, and PowerPoint exports."""

import os
import uuid
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, PatternFill
from pptx import Presentation
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

REPORTS_DIR = os.path.join("static", "reports")
os.makedirs(REPORTS_DIR, exist_ok=True)

# ─── 1. PDF GENERATOR (ReportLab) ───
def generate_pdf_report(title: str, headers: list[str], rows: list[list], summary_text: str) -> str:
    filename = f"report_{uuid.uuid4().hex[:8]}.pdf"
    filepath = os.path.join(REPORTS_DIR, filename)
    
    doc = SimpleDocTemplate(filepath, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
    styles = getSampleStyleSheet()
    
    # Custom Violet Styling (Matching #8776ea)
    primary_color = colors.HexColor("#8776ea")
    
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Title'],
        fontName='Helvetica-Bold',
        fontSize=24,
        textColor=primary_color,
        spaceAfter=15
    )
    
    body_style = styles['Normal']
    
    story = []
    # Title
    story.append(Paragraph(title, title_style))
    story.append(Spacer(1, 15))
    
    # Summary
    if summary_text:
        story.append(Paragraph(f"<b>Executive Summary:</b> {summary_text}", body_style))
        story.append(Spacer(1, 15))
    
    # Table Content
    if headers and rows:
        table_data = [headers] + rows
        col_width = 540 / len(headers)
        t = Table(table_data, colWidths=[col_width]*len(headers))
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), primary_color),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('BOTTOMPADDING', (0,0), (-1,0), 8),
            ('TOPPADDING', (0,0), (-1,0), 8),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#A29DB8")),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor("#F3F1F8")])
        ]))
        story.append(t)
        
    doc.build(story)
    return f"/reports/{filename}"

# ─── 2. EXCEL GENERATOR (openpyxl) ───
def generate_excel_report(title: str, headers: list[str], rows: list[list]) -> str:
    filename = f"report_{uuid.uuid4().hex[:8]}.xlsx"
    filepath = os.path.join(REPORTS_DIR, filename)
    
    wb = Workbook()
    ws = wb.active
    ws.title = "Report"
    
    # Styling Sheet
    font_header = Font(name="Arial", size=11, bold=True, color="FFFFFF")
    fill_header = PatternFill(start_color="8776EA", end_color="8776EA", fill_type="solid")
    align_center = Alignment(horizontal="center", vertical="center")
    
    # Title Block
    if title:
        ws.merge_cells("A1:D1")
        ws["A1"] = title
        ws["A1"].font = Font(name="Arial", size=14, bold=True, color="8776EA")
        ws.row_dimensions[1].height = 30
        ws.append([]) # empty row
        
    # Headers
    if headers:
        ws.append(headers)
        header_row = ws.max_row
        for col_idx in range(1, len(headers) + 1):
            cell = ws.cell(row=header_row, column=col_idx)
            cell.font = font_header
            cell.fill = fill_header
            cell.alignment = align_center
        
    # Rows
    if rows:
        for row in rows:
            ws.append(row)
            
    wb.save(filepath)
    return f"/reports/{filename}"

# ─── 3. POWERPOINT GENERATOR (python-pptx) ───
def generate_pptx_report(title: str, bullets: list[str]) -> str:
    filename = f"report_{uuid.uuid4().hex[:8]}.pptx"
    filepath = os.path.join(REPORTS_DIR, filename)
    
    prs = Presentation()
    
    # Slide 1: Title Slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    slide.shapes.title.text = title
    slide.placeholders[1].text = "Generated by Morepen AI Workspace"
    
    # Slide 2: Bullet points
    if bullets:
        bullet_slide_layout = prs.slide_layouts[1]
        slide2 = prs.slides.add_slide(bullet_slide_layout)
        slide2.shapes.title.text = "Analysis Insights"
        
        tf = slide2.placeholders[1].text_frame
        for i, pt in enumerate(bullets):
            if i == 0:
                tf.text = pt
            else:
                p = tf.add_paragraph()
                p.text = pt
            
    prs.save(filepath)
    return f"/reports/{filename}"
